### PR TITLE
fix toDecimal(.,.) issue in intHash(content)

### PR DESCRIPTION
**Pull request by Thecarisma**
# Description

> Fix the absent of toDecimal block in the intHash block located in the simple.security.Hash module

## Type Of Change

> Please delete options that are not relevant and mark the ones that are relevant.

- [x] Bug Fix: Non breaking change which fixes an issue.

## Briefly Explain Why This PR Should Be Merged.

This PR fixes issues with generating intHash of a string

## How Has This Been Tested ?

> This has been tested using snippet to validate the block 

## Checklist:

- [ ] I have created a supporting issue for this PR.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests passed locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Youngestdev** [comment]
I'll review this.

**Comment by Thecarisma** [comment]
> stdout - is the default operating system standard output, cmd on win, terminal on linux
> stderr - is the default os error output, cmd on win, terminal on linux
> stdin - is the default os standard method of accepting input keyboard on most os

These variable are the reason the **final** keyword was needed in the first place to ensure they are never changed even though printing can be piped to other standards. the use of `stdout.printfc(ConsoleColor.BLUE(), " ")` indicates that the a string `" "` should be printed to the standard output `stdout` changing the color of the text to `BLUE`. 
This block is also available for `stderr` and there is a delegate block on it own that does similar function but rather accept the output stream as the first parameter `printfc(..)` block itself. The reason for the bare block is when user decide to use another stream for his or an output,
> Note that the sdtout and stderr are just plain file
E.g the output can be sent to a file instead of the stdout 
```
file = new File("../logstdout.log")
print(file, "logging to our log")
```
The snippet ablove log into the `logstdout.log` file instead of stdout or stderr 
```
sdtout.print("logging to output file") //forces the string to the os standard output. refer above
sdterr.print("logging to output file") //forces the string to the os standard error. refer above 
print(stdout,"logging to output file") //log the string to the os standard output by our choice
print(customLog,"logging to output file") //log the string to a customLog by our choice
```

When simple-lang documentation has start it will be well documented

**Comment by Youngestdev** [comment]
Unfortunately it doesn't, instead, it brings the error **Calling block without definition : print **. I think the `std_output` block isn't set to take in arguments from an object file yet ? .

> The snippet ablove log into the logstdout.log file instead of stdout or stderr

**Comment by Youngestdev** [comment]
So will you implement it now so it's added to this PR or you'll want it to be a new PR ?

**Comment by Thecarisma** [comment]
Close this PR it ll make a new PR when the Console is done

**Comment by Youngestdev** [comment]
Close this PR ? No. Will there be any reduction from the current code in this PR ? I'll merge this PR for now. You can send another PR when the console is worked on.

**Pull request merged**
