### PR TITLE
Fixed MakeFile and build file.

### PR DESCRIPTION
**Pull request by Youngestdev**
Fixed this in regards to the recent PR #29

### CODE REVIEW

**Comment by Thecarisma** [comment]
removing the function **cc_fprintf** in consoler.c source will render it useless and it won't compile which will make build fail. Also the **finalize_installation()** is used to install simplepad on Ubuntu variant Linux systems and also for linking the simple executable and libraries.

Since the build scripts are made to be fail safe these lines
```bash
        mkdir -p $(DESTDIR)$(PREFIX)/bin
	mkdir -p $(DESTDIR)$(PREFIX)/lib
	mkdir -p $(DESTDIR)$(PREFIX)/include/simple
```

Are used to check if the directory exists else it is created. They are harmless

**Comment by Youngestdev** [comment]
No, you're wrong, it'll make it compile instead. There is duplication of
that function, I urge you to rebuild your Linux build. So allow the PR to
pass also, it's not ideal to leave those line to stay ( harmless code ) .
Every Linux system comes with those directories pre-created.

**Comment by Youngestdev** [comment]
Oh, you could add the simplepad back, but I think its of no use because,
simple pad will be installed when the Environments makefile is executed.

On Sep 9, 2018 17:41, "Abdulazeez Abdulazeez Adeshina" <
laisibizness@gmail.com> wrote:

No, you're wrong, it'll make it compile instead. There is duplication of
that function, I urge you to rebuild your Linux build. So allow the PR to
pass also, it's not ideal to leave those line to stay ( harmless code ) .
Every Linux system comes with those directories pre-created.

**Comment by Youngestdev** [comment]
consoler-error

**Pull request closed without merging**
