### PR TITLE
Fix long pathname segfault problem

### PR DESCRIPTION
**Pull request by appcypher**
This fixes the segfaulting issue caused by passing long path names to `call`.

### CODE REVIEW

**Comment by appcypher** [comment]
Don't mind the line ending changes, my VSCode automatically changes the crlf to newlines.

BTW, since this a cross-platform open-source project, it may make sense to use Unix line endings in all files.

You can set this up on ur git.

More info: 
[Dealing with lineendings in git](https://help.github.com/articles/dealing-with-line-endings/)
[Why using \n is preferred](https://superuser.com/questions/514989/proper-line-ending-for-an-open-source-php-project)
[Line endings on different platforms](https://en.wikipedia.org/wiki/Newline)

**Comment by Youngestdev** [comment]
I assume this works perfectly on your Mac . I'll merge :+1:

**Comment by appcypher** [comment]
It does. Won't raise a PR otherwise

**Comment by Youngestdev** [comment]
I'm not using a Mac. So, just to be sure
 Cheers.

**Pull request merged**
