### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Youngestdev**
Changes casing.

### CODE REVIEW

**Comment by Thecarisma** [comment]
this commit is destructive you removed the entire sources and include.
I guess what you want to do is remove dependency folders in your bootsrc but went ahead and remove the bootsrc folder. This commit can never be merged until it is reviewed

**Comment by Thecarisma** [comment]
you will have to re-add the bootsrc folder

**Comment by Youngestdev** [comment]
That was a mistake. I'll resend the PR 🙏🙏

**Comment by Youngestdev** [comment]
For a terrible mistake.m I'll resend PR. I'm sorry once again

**Pull request closed without merging**
