### PR TITLE
FEATURE : implements calling file by module name e.g simple.core.String

### PR DESCRIPTION
**Pull request by Thecarisma**
Add a new feature to the simple-lang to allow calling file using it module name in relativity to the simple source file and also import the module e.g 
```
call simple.core.String
```
The call statements expands to 
```simple
call "simple/core/String.sim" ? simple.core
```
The last part of the statement e.g `String` is the file name `String.sim` located in the previous parts folder `simple.core.` which is `simple/core/` and also import the module `simple.core` in the file. If the module does not exist in the file it result to **RUNTIME ERROR 24**.

### CODE REVIEW

**Comment by Youngestdev** [comment]
I expected an example demonstrating these additions.

**Comment by Thecarisma** [comment]
Let the Console be it intended as it still in development the aim of this PR is is the new `call` feature. 
i ll add example to demonstrate the new feature

**Comment by Youngestdev** [comment]
Okay, some call to modules don't work -  the Number and List module. I think the problem will be from the module itself. When I ran a brief example for the List and Number module. I got a message like this..
```
Line 1 -> Syntax error : Unexpected '26'
        in file List.sim
```
Weird tho.

Back to the Console module, remember the **simplerepl** enviroment, depends on that module sternly. 
So, any idea what might be the cause of the error's i'm getting ?

**Comment by Thecarisma** [comment]
added example (https://github.com/simple-lang/simple/pull/34/commits/202816d235f0f52413acc971942e95961f8049ff#diff-5947e7037dde22467de224716851f929)[https://github.com/simple-lang/simple/pull/34/commits/202816d235f0f52413acc971942e95961f8049ff#diff-5947e7037dde22467de224716851f929]

**Comment by Thecarisma** [comment]
I ll check the modules examples

**Comment by Youngestdev** [comment]
Good.. Check them and peep at why the List and Number module call path is erroneous. Would've checked it, kinda busy .

**Comment by Youngestdev** [comment]
Now, I figured out something.

**Comment by Youngestdev** [comment]
You didn't run the example you sent, did you ? NO I'm sure. When I ran your example the web module threw an error, I've fixed that already in my machine .

**Comment by Thecarisma** [comment]
Fixed the simple-repl and the module call issues

**Comment by Youngestdev** [comment]
I'm afraid we'll have to restore the web modules back to the way it used to be... I mean returning the classes back to independent files.. What do you think ?

**Comment by Youngestdev** [comment]
I'll check it out now.
> Fixed the simple-repl and the module call issues

**Comment by Thecarisma** [comment]
> I'll check it out now.
> 
> > Fixed the simple-repl and the module call issues

There is no need for that i have fixed the web module in my last commit

**Comment by Youngestdev** [comment]
I'm moving the web/front modules to the way it was before.

> > I'll check it out now.
> > > Fixed the simple-repl and the module call issues
> 
> There is no need for that i have fixed the web module in my last commit

**Comment by Thecarisma** [comment]
screenshot 73
screenshot 74
screenshot 75

**Pull request merged**
