### PR TITLE
FEATURES : A more elegant and elevated OOP

### PR DESCRIPTION
**Pull request by Thecarisma**
# Description

> The OOP part of the lang has been elevated with some features addition listed below :
 - adding the `getter` and `setter` blocks to change behavior of a variable or attributes when they are assigned or requested
 - allow the use of braces to access class object for more cleaner code. This feature is added for a more cleaner and compact syntax for classes that requires numerous attributes to be changed and thus make the code shorter e.g 
**Vintage Style**
```
test = new Test
test.Name = "A. Azeez"
test.Gender = "boy"
test.Age = 25
```
**Braces Style**
```
test = new Test { Name = "A. Azeez" Gender = "boy" Age = 25 }
```
Even though both style can be written in one line the second style also allow the braces to compound the current object that is been worked on and also reduce the number of character typed

 - Changing the behavior of **operators** : Now all object in simple can define a custom behavior or function for an operator such that object can be concatenated e.g 
```
a = new TestClass { value = 30 }
b = new TestClass { value = 70 }
c = a + b 
@c.Value
```
it throws an operator not supported on type error, but in a situation whereby the operator behavior has been defined in the class it will be effected 
```
a = new TestClass { value = 30 }
b = new TestClass { value = 70 }
c = a + b 
@c.Value //outputs 100

class TestClass

    value = 30

    block operator(operator,parameter)
        switch operator {
            case "+"
                value += parameter.value
        }
        return this
```

## Type Of Change

> Please delete options that are not relevant and mark the ones that are relevant.

- [x] Bug Fix: Non breaking change which fixes an issue.
- [x] New feature: Non breaking change which adds a new functionality ( module, enviroment etc).
- [ ] Breaking change - Fixes a feature that would cause existing functionality to not work as expected.
- [ ] Documentation - Module or general documentation.

## Briefly Explain Why This PR Should Be Merged.
This PR should be merge to completely introduce this new OOP features to the simple

## How Has This Been Tested ?

> This new features has been tested by adding the following test files in the [examples/basic](https://github.com/simple-lang/simple/tree/master/examples/basic) folder 
 - [braceupclass.sim](https://github.com/Thecarisma/simple/blob/master/examples/basic/braceupclass.sim)
 - [gettersetter.sim](https://github.com/Thecarisma/simple/blob/master/examples/basic/gettersetter.sim)
 - [operators.sim](https://github.com/Thecarisma/simple/blob/master/examples/basic/operators.sim)

## Checklist:

- [x] I have created a supporting issue for this PR.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests passed locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Youngestdev** [comment]
I'll be reviewing this.

**Comment by Youngestdev** [comment]
I havent run the examples yet but I know the results. However, can we create classes with empty variables ?

**Comment by Youngestdev** [comment]
Mistakenly closed it.

**Comment by Thecarisma** [comment]
very well classes can be created with empty value but it is better to initialize the variable when declare maybe to null so it will be readable such as instead of `value` use `value = null` instead.

```js

t1 = new TestClass {value = 1 }
t2 = new TestClass {value = 9 }
t1 = t1+t2
@t1.value

class TestClass
  // Empty value
    value

    block operator(operator,parameter)
        switch operator {
            case "+"
                value += parameter.value
        }
        return this
```

This output `10` correctly

**Comment by Youngestdev** [comment]
Okay, then this PR is going to be merged and let's start rocking the new style for class values declaration :tada:

**Comment by Youngestdev** [comment]
So from the code below ....

```js
a = new TestClass { value = 30 }
b = new TestClass { value = 70 }
c = a + b 
@c.Value //outputs 100

class TestClass

    value = 30

    block operator(operator,parameter)
        switch operator {
            case "+"
                value += parameter.value
        }
        return this

```

This will also return 100 right ?

```js

x = new TestClass
x.value  = 30
y = new TestClass
y.value = 70
result = x.operator(+, y) // This should result to 100 isn't it ?

**Comment by Thecarisma** [comment]
```
x = new TestClass
x.value  = 30
y = new TestClass
y.value = 70
result = x.operator("+", y) // This result to an instance of TestClass with value of 100
@result.value //results to 100
```

**Comment by Youngestdev** [comment]
Nice!. Dynamic OOP functions and method !.

**Comment by Youngestdev** [comment]
How about Classes that have constructor ? Do they follow the new pattern .

**Comment by Thecarisma** [comment]
No and Yess
### No

A class having a constructor will have issue while using braces to access it children as the braces check if the Object is a class therefore calling the constructor using `()` before or after the braces will result to error
```js
a = new TestClass() { value = 30 } //error
a = new TestClass { value = 30 }() //error big one
```

### YES
> Braces access not limited to initialization only. 
The class object and methods can be accessed using braces at anytime in the program e.g 
```js
a = new TestClass() 
a { value = 30 } //valid
```

> The constructor can choose to return an instance of that object
```js
a = new TestClass() { value = 30 } //error
```
is an error but in a situation whereby the constructor return an instance of the class it is valid. The gramer for the brace is the brace check if the previous item is a class e.g 
```js
"name" { } //invalid
new String("name") { } //valid
```

so this will execute successfullty
```js
a = new TestClass() { value = 30 }

class TestClass 
    ...
    block TestClass()
          return this //which is very rare and not advisable
```

**Comment by Thecarisma** [comment]
`return value` just return the parameter which can be string, number or list , `return this` return an instance of the TestClass with all the class values 
`return this` same as `return new TestClass`

**Comment by Thecarisma** [comment]
returning in a Constructor is a very very very bad practice and should be avoided by all means

**Comment by Youngestdev** [comment]
Well, my question looks unanswered still.

Take this block of code:

```js
a = new TestClass() { value = 30 }

class TestClass 
   __OBJECT = ""
  __OBJECT_NAME = "String"

    block TestClass(value)
          __OBJECT = value
          return __OBJECT

```

Normally, we'll instantiate an instance of that class like this..

```js
test = new TestClass("Abdul")
```

But with this new development, it'll be void : 

```js
test = new TestClass() { value = "Abdul" }
```

Instead, 

```
test = new TestClass("test") {}
```
Well, with this changes it's pretty nice and can be confusing :smile:

**Pull request merged**
