### PR TITLE
Resolve errors arising from new list update

### PR DESCRIPTION
**Pull request by Thecarisma**
# Description

> This PR resolves all the error in the simple-lang modules that arise after updating the list core behaviour.

 - Efficient check in the [Windows-Build.bat](https://github.com/simple-lang/simple/blob/master/build/Windows-Build.bat) to determine the C/C++ build toolchain correctly
 - Add more examples for the new OOP Features
 - Create unit test files in each folder in examples folder 

## Type Of Change

> Please delete options that are not relevant and mark the ones that are relevant.

- [x] Bug Fix: Non breaking change which fixes an issue.
- [ ] New feature: Non breaking change which adds a new functionality ( module, environment etc).
- [ ] Breaking change - Fixes a feature that would cause existing functionality to not work as expected.
- [ ] Documentation - Module or general documentation.

## Briefly Explain Why This PR Should Be Merged.
This PR should be merge ASAP as the modules is presumably unusable due to changes in the list behavior

## How Has This Been Tested ?

> This has been thoroughly tested by running a general unit test on the entire sample files in th examples folder using the following files 

 - [unit_test.sim](https://github.com/Thecarisma/simple/blob/master/examples/unit_test.sim)
 - [algorithms/unit_test.sim](https://github.com/Thecarisma/simple/blob/master/examples/algorithms/unit_test.sim)
 - [basic/unit_test.sim](https://github.com/Thecarisma/simple/blob/master/examples/basic/unit_test.sim)
 - [gui/unit_test.sim](https://github.com/Thecarisma/simple/blob/master/examples/gui/unit_test.sim)
 - [intermediate/unit_test.sim](https://github.com/Thecarisma/simple/blob/master/examples/intermediate/unit_test.sim)
 - [internetandparser/unit_test.sim](https://github.com/Thecarisma/simple/blob/master/examples/internetandparser/unit_test.sim)
 - [modules/unit_test.sim](https://github.com/Thecarisma/simple/blob/master/examples/modules/unit_test.sim)
 - [syntax/unit_test.sim](https://github.com/Thecarisma/simple/blob/master/examples/syntax/unit_test.sim)

## Checklist:

- [ ] I have created a supporting issue for this PR.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests passed locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Youngestdev** [comment]
I'll be reviewing this unfailingly tomorrow.

**Comment by Youngestdev** [comment]
First, I'm surprised you were trying to overwrite final variables well knowing they can't be overwritten. That blocked the installation because the DynamicModule list variable in `DynamicLoader.sim` file is a final var.

```
final __mainDynaicModulesCount = 0

final __mainDynaicModules = [	
		["systemic.dll", "string_savant.dll"],		#Windows
		["systemic.so", "string_savant.so"],		#Linux
		["systemic.dylib", "string_savant.dylib"] 	#MAC
	]
```

Here again:

```

final dynamicModules = []

```

Then, you tried to overwrite the variable : 

```
__mainDynaicModulesCount++
```

Secondly, you didn't change the names of the String module blocks in `bake.sim`. You renamed a few blocks but didn't change them in `bake.sim`.

Thirdly, I don't know why bake isn't building, perhaps check it. Also, I had to comment out the `png_write` line in fulltick module until a better solution is given off.

**Comment by Thecarisma** [comment]
I ll check it

**Comment by Youngestdev** [comment]
I fixed them already so you've gotta check why bake doesn't work.

**Comment by Thecarisma** [comment]
You can commit leave bake for the next two PR

**Comment by Youngestdev** [comment]
> You can commit leave bake for the next two PR

Okay then..

**Pull request merged**
